# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scraper',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/scraper',
                'lib_path': 'scraper'},
  'syms': {'scraper.core': {'scraper.core.foo': ('core.html#foo', 'scraper/core.py')}}}
